-Ivendor/ibex/vendor/picorv32
rtl/microsoc_top.sv
rtl/processor_block/processor_block.sv
rtl/processor_block/riscv_core_wrapper.sv
firmware/bootrom.sv
vendor/picorv32/picorv32.v
rtl/peripheral_block/peripheral_block.sv
rtl/peripheral_block/gpio_controller.sv
rtl/peripheral_block/ram.sv
rtl/peripheral_block/timer32.sv
